export const AnswerFilters = [
  { name: "Highest Upvotes", value: "highestUpvotes" },
  { name: "Lowest Upvotes", value: "lowestUpvotes" },
  { name: "Most Recent", value: "recent" },
  { name: "Oldest", value: "old" },
];

export const UserFilters = [
  { name: "New Users", value: "new_users" },
  { name: "Old Users", value: "old_users" },
  { name: "Top Contributors", value: "top_contributors" },
];

export const QuestionFilters = [
  { name: "Most Recent", value: "most_recent" },
  { name: "Oldest", value: "oldest" },
  { name: "Most Voted", value: "most_voted" },
  { name: "Most Viewed", value: "most_viewed" },
  { name: "Most Answered", value: "most_answered" },
];

export const TagFilters = [
  { name: "Popular", value: "popular" },
  { name: "Recent", value: "recent" },
  { name: "Name", value: "name" },
  { name: "Old", value: "old" },
];

export const HomePageFilters = [
  { name: "Newest", value: "newest" },
  { name: "Recommended", value: "recommended" },
  { name: "Frequent", value: "frequent" },
  { name: "Unanswered", value: "unanswered" },
];

export const GlobalSearchFilters = [
  { name: "Question", value: "question" },
  { name: "Answer", value: "answer" },
  { name: "User", value: "user" },
  { name: "Tag", value: "tag" },
];

export const CountryFilters = [
  { name: "Afghanistan", value: "afghanistan" },
  { name: "Argentina", value: "argentina" },
  { name: "Australia", value: "australia" },
  { name: "Austria", value: "austria" },
  { name: "Bangladesh", value: "bangladesh" },
  { name: "Belgium", value: "belgium" },
  { name: "Brazil", value: "brazil" },
  { name: "Canada", value: "canada" },
  { name: "Chile", value: "chile" },
  { name: "China", value: "china" },
  { name: "Colombia", value: "colombia" },
  { name: "Cuba", value: "cuba" },
  { name: "Denmark", value: "denmark" },
  { name: "Egypt", value: "egypt" },
  { name: "Ethiopia", value: "ethiopia" },
  { name: "Finland", value: "finland" },
  { name: "France", value: "france" },
  { name: "Germany", value: "germany" },
  { name: "Greece", value: "greece" },
  { name: "Hungary", value: "hungary" },
  { name: "India", value: "india" },
  { name: "Indonesia", value: "indonesia" },
  { name: "Iran", value: "iran" },
  { name: "Iraq", value: "iraq" },
  { name: "Ireland", value: "ireland" },
  { name: "Israel", value: "israel" },
  { name: "Italy", value: "italy" },
  { name: "Japan", value: "japan" },
  { name: "Jordan", value: "jordan" },
  { name: "Kenya", value: "kenya" },
  { name: "South Korea", value: "south korea" },
  { name: "Lebanon", value: "lebanon" },
  { name: "Malaysia", value: "malaysia" },
  { name: "Mexico", value: "mexico" },
  { name: "Morocco", value: "morocco" },
  { name: "Nepal", value: "nepal" },
  { name: "Netherlands", value: "netherlands" },
  { name: "New Zealand", value: "new zealand" },
  { name: "Nigeria", value: "nigeria" },
  { name: "Norway", value: "norway" },
  { name: "Pakistan", value: "pakistan" },
  { name: "Peru", value: "peru" },
  { name: "Philippines", value: "philippines" },
  { name: "Poland", value: "poland" },
  { name: "Portugal", value: "portugal" },
  { name: "Qatar", value: "qatar" },
  { name: "Romania", value: "romania" },
  { name: "Russia", value: "russia" },
  { name: "Saudi Arabia", value: "saudi arabia" },
  { name: "Singapore", value: "singapore" },
  { name: "South Africa", value: "south africa" },
  { name: "Spain", value: "spain" },
  { name: "Sri Lanka", value: "sri lanka" },
  { name: "Sweden", value: "sweden" },
  { name: "Switzerland", value: "switzerland" },
  { name: "Syria", value: "syria" },
  { name: "Taiwan", value: "taiwan" },
  { name: "Thailand", value: "thailand" },
  { name: "Turkey", value: "turkey" },
  { name: "Ukraine", value: "ukraine" },
  { name: "United Arab Emirates", value: "united arab emirates" },
  { name: "United Kingdom", value: "united kingdom" },
  { name: "United States", value: "united states" },
  { name: "Venezuela", value: "venezuela" },
  { name: "Vietnam", value: "vietnam" },
  { name: "Yemen", value: "yemen" },
  { name: "Zimbabwe", value: "zimbabwe" },
];
